services:
  app-backend-service-epic-score-bot:
    build:
      context: EpicScoreBot
      dockerfile: Dockerfile
    hostname: app-backend-service-epic-score-bot
    container_name: app-backend-service-epic-score-bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - VOLUME_PATH=${VOLUME_PATH}
      - CONFIG_FILEPATH=${CONFIG_FILEPATH}
      - CONFIG_FILENAME=${CONFIG_FILENAME}
    volumes:
      - backend-service-epic-score-bot:${VOLUME_PATH}
    networks:
      - back-tier

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=epic-score-db
      - POSTGRES_USER=epicbot
      - POSTGRES_PASSWORD=epicbot@
    # command:
    #   - 'echo "host skygrowdb krassor all trust" >> /var/lib/postgresql/data/pg_hba.conf'
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgres
    networks:
      - back-tier

volumes:
  pg-data:
  backend-service-epic-score-bot:


networks:
  back-tier:
